routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/admin/logout', ['uses' => 'Panel\UserController@admin_logout', 'as' => 'admin_logout']);

Route::get('/', 'Front\HomeController@index')->name('home');
Route::get('/admin', 'Panel\HomeController@panel')->name('admin');

//Panel routes
Route::group(['prefix' => 'admin'], function() {
    Route::resource('users','Panel\UserController');
    Route::resource('abilities','Panel\AbilityController');
    Route::resource('roles','Panel\RoleController');
    Route::resource('menu','Panel\MenuController');
    Route::resource('pages','Panel\PageController');
});

/* PANE ROUTES */

Route::post('/admin/change_active_user', 'Panel\UserController@changeActive');
Route::post('/admin/change_admin_user', 'Panel\UserController@changeAdmin');
Route::post('/admin/assign_new_role', ['uses' => 'Panel\UserController@assignrole','as' => 'assign_new_role']);
Route::post('/admin/remove_role/{user}/{role_name}', ['uses' => 'Panel\UserController@removeRole','as' => 'remove_role']);

Route::post('/admin/change_active_role', 'Panel\RoleController@changeActive');
Route::post('/admin/assign_new_ability', ['uses' => 'Panel\RoleController@assignAbility','as' => 'assign_new_ability']);
Route::post('/admin/remove_ability/{role_name}/{ability_id}', ['uses' => 'Panel\RoleController@removeAbility','as' => 'remove_ability']);

Route::post('/admin/change_active_ability', 'Panel\AbilityController@changeActive');

Route::post('/admin/change_active_menu', 'Panel\MenuController@changeActive');

Route::post('/admin/change_active_page', 'Panel\PageController@changeActive');

Route::get('/admin/new_page', ['uses' => 'Panel\PageController@newPage', 'as' => 'new_page_form']);
Route::get('/admin/my_account', ['uses' => 'Panel\UserController@getMyAccount', 'as' => 'admin_my_account']);

/* FRONT ROUTES */

Route::get('/about-me', ['uses' => 'Front\HomeController@aboutMe', 'as' => 'about-me']);
Route::get('/page/download/{filename}', ['uses' => 'Front\HomeController@downloadFile', 'as' => 'download_file']);
Route::get('/page/{page_slug}', ['uses' => 'Front\PageController@showPage', 'as' => 'show_page']);

Route::get('/generate-sitemap', ['uses' => 'Front\HomeController@generateSitemap', 'as' => 'generate_sitemap']);

resources/views/admin/admin.blade.php
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{{URL::asset('css/bootstrap.min.css')}}"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{{ URL::asset('css/main.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('css/jquery-ui.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('css/pretty-checkbox.min.css') }}">


    <script type="text/javascript" src="{{URL::asset('js/jquery-3.2.1.js') }}"></script>
    <script type="text/javascript" src="{{URL::asset('js/jquery-ui.js') }}"></script>
    <script type="text/javascript" src="{{URL::asset('js/jquery.sticky.js') }}"></script>
    <script type="text/javascript" src="{{URL::asset('js/bootstrap.min.js')}}"></script>
    <script type="text/javascript" src="{{URL::asset('js/main.js')}}"></script>
    <script type="text/javascript" src="{{URL::asset('js/select2.min.js')}}"></script>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>

    <link rel="stylesheet" href="https://unpkg.com/simplebar@latest/dist/simplebar.css" />
    <script src="https://unpkg.com/simplebar@latest/dist/simplebar.js"></script>

    <title>almono's CMS application</title>
</head>

<body style="background: #464646">
    <div class="wrapper">
        <nav id="sidebar" style="position: fixed">
            @include('admin.sidebar')
        </nav>
        <div id="content">
            @yield('admin-content')
        </div>
    </div>
</body>
</html>

@yield('admin-scripts')

<script type="text/javascript">
    $(document).ready(function () {

        $('#sidebarCollapse').on('click', function () {
            $('#sidebar, #content').toggleClass('active');
            $('.collapse.in').toggleClass('in');
            $('a[aria-expanded=true]').attr('aria-expanded', 'false');
        });

    });

    function ConfirmDelete()
    {
        var x = confirm("Are you sure you want to delete?");
        if (x)
            return true;
        else
            return false;
    }

</script>

resources/views/admin/cms_abilities.blade.php
@extends('admin.admin')
@section('admin-content')
    @include('admin.cms_admin_content_top')
    <div class="col-xs-12 padding_fix" style="padding-top: 15px; position: relative;">
        <a class="btn btn-new" id="new_ability_add" style="float: right;"><i class="fa fa-plus" style="padding-right: 5px;"></i>Add new ability</a>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 new_user_div" id="new_ability_div">
            {!! Form::open(array('route' => 'abilities.store')) !!}
            {!! Form::token() !!}
            <div class="form-row">
                <div class="form-group col-md-12">
                    @if ($errors->has('title'))
                        <div class="error" style="color: red; font-size: 12px;">
                            {{ $errors->first('title') }}
                        </div>
                    @endif
                    <label class="new_user_label" for="inputAbilityName">Ability name</label>
                    <input type="text" class="form-control" id="inputAbilityName" name="ability_name" placeholder="Ability name" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-xs-12 text-center">
                    <button class="btn btn-new" type="submit" value="Create new permission">Create new ability</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
    <div class="col-xs-12 users-content padding_fix">
        <div class="col-xs-12 padding_fix cms-headings" style="border-bottom: 1px solid #222; height: 30px;">
            <div class="col-xs-12 col-sm-12 col-md-2 text-center" style="color: white; line-height: 30px;">
                <span>Name</span>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-1 text-center" style="color: white; line-height: 30px;">
                <span>Active</span>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-2 text-center hidden-xs hidden-sm" style="color: white; line-height: 30px;">
                <span>Created on</span>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-1 text-center" style="color: white; line-height: 30px;">
                <span>Delete</span>
            </div>

        </div>
        @if(count($abilities) > 0)
            <div class="abilities_list">
                @include('admin.partials.cms_ability_listing')
            </div>
        @else
            <div class="col-xs-12 padding_fix text-center" style="color: white; padding-top: 10px; padding-bottom: 10px;">
                There are no abilities to display
            </div>
        @endif
    </div>
@stop
@section('admin-scripts')
    <script type="text/javascript">

        $(document).ready( function() {
            $('#new_ability_add').click( function() {
                $('#new_ability_div').toggle("fast");
            });
        });


        $('.is-active').click( function() {
            var id = $(this).attr('id');

            $.ajax({
                type: 'POST',
                url: 'change_active_ability',
                data: {
                    "_token": "{{ csrf_token() }}",
                    "id": this.id
                },
                success: function(data){
                }
            });
        });

        $(function() {
            $('body').on('click', '.pagination a', function(e) {
                e.preventDefault();

                $('.abilities_list a').css('color', '#1eb91e');

                var url = $(this).attr('href');
                getAbilities(url);
                window.history.pushState("", "", url); // sets url to current pagination href
            });

            function getAbilities(url) {
                $.ajax({
                    url : url
                }).done(function (data) {
                    $('.abilities_list').html(data);
                }).fail(function () {
                    alert('Abilities could not be loaded.');
                });
            }
        });

    </script>
@stop

resources/views/admin/cms_admin_content_top.blade.php
@if (session()->has("flash_notification"))
    @include('flash::message')
@endif

resources/views/admin/cms_edit_menu.blade.php
@extends('admin.admin')
@section('admin-content')
    @include('admin.cms_admin_content_top')
    <div class="col-xs-12 users-content">
        <div class="row">
            <div class="col-xs-12" style="padding: 20px 15px;">
                <span style="font-size: 30px; font-weight: 600;">Edit menu item</span>
            </div>
            <div class="col-xs-12" style="padding-top: 20px;">
                {!! Form::open(array('route' => [ 'menu.update', $menu ], 'files' => 'true', 'method' => 'PUT' )) !!}
                {!! Form::token() !!}
                <div class="form-row col-xs-12 col-sm-3 col-md-3 padding_fix">
                    <div class="form-group col-xs-12 col-sm-12" style="padding-top: 10px;">
                        <div class="col-xs-12 col-sm-12 padding_fix" style="margin-bottom: 20px;">
                            @if ($errors->has('title'))
                                <div class="error" style="color: red; font-size: 12px;">
                                    {{ $errors->first('title') }}
                                </div>
                            @endif
                            <div class="col-xs-4 text-right border-right-1">
                                <label class="new_user_label" for="inputTitle4">Title</label>
                            </div>
                            <div class="col-xs-8 text-left">
                                <div>{{ $menu->menu_name }}</div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 padding_fix" style="margin-bottom: 20px;">
                            <div class="col-xs-4 text-right border-right-1">
                                <label class="new_user_label" for="inputSeo4">URL</label>
                            </div>
                            <div class="col-xs-8 text-left">
                                <div>{{ $menu->menu_url }}</div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 padding_fix" style="margin-bottom: 20px;">
                            <div class="col-xs-4 text-right border-right-1">
                                <label class="new_user_label" for="inputSeo4">Order</label>
                            </div>
                            <div class="col-xs-8 text-left">
                                <div>{{ $menu->order }}</div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 padding_fix" style="margin-bottom: 20px;">
                            <div class="col-xs-4 text-right border-right-1">
                                <label class="new_user_label" for="inputSeo4">Parent item</label>
                            </div>
                            <div class="col-xs-8 text-left">
                                @if(isset($menu->parent) && !is_null($menu->parent))
                                    <div>{{ $menu->parent->menu_name }}</div>
                                @else
                                    <div>No parent assigned</div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-row col-xs-12 col-sm-8 col-md-8 padding_fix">
                    <div class="form-group col-xs-12 col-sm-12" style="padding-top: 10px;">
                        <div class="col-xs-12 col-sm-12 flex_display padding_fix" style="margin-bottom: 10px;">
                            @if ($errors->has('new_name'))
                                <div class="error" style="color: red; font-size: 12px;">
                                    {{ $errors->first('new_name') }}
                                </div>
                            @endif
                            <div class="col-xs-2 padding_fix text-center">
                                <label class="new_user_label" for="inputTitle4">New Title</label>
                            </div>
                            <div class="col-xs-10">
                                <input type="text" class="form-control" id="inputTitle4" name="new_name" placeholder="{{ $menu->menu_name }}" style="max-width: 200px;">
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 flex_display padding_fix" style="margin-bottom: 10px;">
                            @if ($errors->has('new_url'))
                                <div class="error" style="color: red; font-size: 12px;">
                                    {{ $errors->first('new_url') }}
                                </div>
                            @endif
                            <div class="col-xs-2 padding_fix text-center">
                                <label class="new_user_label" for="inputURL4">New URL</label>
                            </div>
                            <div class="col-xs-10">
                                <input type="text" class="form-control" id="inputTitle4" name="new_url" placeholder="{{ $menu->menu_url }}" style="max-width: 200px;">
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 flex_display padding_fix" style="margin-bottom: 10px;">
                            @if ($errors->has('new_order'))
                                <div class="error" style="color: red; font-size: 12px;">
                                    {{ $errors->first('new_order') }}
                                </div>
                            @endif
                            <div class="col-xs-2 padding_fix text-center">
                                <label class="new_user_label" for="inputOrder4">New Order</label>
                            </div>
                            <div class="col-xs-10">
                                <input type="number" class="form-control" id="inputTitle4" name="new_order" placeholder="{{ $menu->order }}" min="0" style="max-width: 200px;">
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 flex_display padding_fix">
                            <div class="col-xs-2 padding_fix text-center">
                                <label class="new_user_label" for="inputParentName">Parent menu</label>
                            </div>
                            <div class="col-xs-10">
                                <select class="form-control" name="menu_parent" style="max-width: 200px;">
                                    <option value="" @if($menu->parent_id == 0) selected @endif>No parent</option>
                                    @foreach($menu_main as $mm)
                                        <option value="{{$mm->id}}" @if($menu->parent_id == $mm->id) selected @endif>{{ $mm->menu_name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-row col-xs-12 col-sm-12 col-md-5">
                    <div class="form-group col-xs-12 text-center">
                        <button class="btn btn-new" type="submit" value="Update page">Update</button>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@stop

resources/views/admin/cms_edit_page.blade.php
@extends('admin.admin')
@section('admin-content')
    @include('admin.cms_admin_content_top')
    <div class="col-xs-12 users-content">
        <div class="row">
            <div class="col-xs-12" style="padding: 20px 15px;">
                <span style="font-size: 30px; font-weight: 600;">New page creator</span>
            </div>
            <div class="col-xs-12" style="padding-top: 20px;">
                {!! Form::open(array('route' => [ 'pages.update', $page ], 'files' => 'true', 'method' => 'PUT' )) !!}
                {!! Form::token() !!}
                <div class="form-row col-sm-12 padding_fix">
                    <div class="form-group col-xs-12 col-sm-3">
                        <div class="col-xs-12 padding_fix text-center">
                            <img src="{{ asset('page_images/' . $page->page_image . '.jpg') }}" class="img-responsive" style="max-width: 150px;">
                        </div>
                    </div>
                    <div class="form-group col-xs-12 col-sm-9" style="padding-top: 10px;">
                        <div class="col-xs-12 col-sm-12 flex_display padding_fix" style="margin-bottom: 20px;">
                            @if ($errors->has('title'))
                                <div class="error" style="color: red; font-size: 12px;">
                                    {{ $errors->first('title') }}
                                </div>
                            @endif
                            <div class="col-xs-2 padding_fix text-center">
                                <label class="new_user_label" for="inputTitle4">Title</label>
                            </div>
                            <div class="col-xs-10">
                                <input type="text" class="form-control" id="inputTitle4" name="page_title" placeholder="Title" value="{{ $page->page_title }}" required>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 flex_display padding_fix" style="margin-bottom: 20px;">
                            @if ($errors->has('seo'))
                                <div class="error" style="color: red; font-size: 12px;">
                                    {{ $errors->first('seo') }}
                                </div>
                            @endif
                                <div class="col-xs-2 padding_fix text-center">
                                    <label class="new_user_label" for="inputSeo4">SEO Title</label>
                                </div>
                                <div class="col-xs-10">
                                    <input type="text" class="form-control" id="inputSeo4" name="seo" placeholder="Title used for SEO"  value="{{ $page->seo_title }}">
                                </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 flex_display padding_fix" style="margin-bottom: 20px;">
                            @if ($errors->has('seo_desc'))
                                <div class="error" style="color: red; font-size: 12px;">
                                    {{ $errors->first('seo_desc') }}
                                </div>
                            @endif
                            <div class="col-xs-2 padding_fix text-center">
                                <label class="new_user_label" for="inputSeo4">SEO Desc</label>
                            </div>
                            <div class="col-xs-10">
                                <input type="text" class="form-control" id="inputSeo4" name="seo_desc" placeholder="Description used for SEO"  value="{{ $page->seo_description }}">
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-12 flex_display padding_fix">
                            @if ($errors->has('page_image'))
                                <div class="error" style="color: red; font-size: 12px;">
                                    {{ $errors->first('page_image') }}
                                </div>
                            @endif
                            <div class="col-xs-2 padding_fix text-center">
                                <label class="new_user_label" for="inputPageImage4">Page image</label>
                            </div>
                            <div class="col-xs-10">
                                <input type="file" id="inputPageImage4" name="page_image"  value="{{ $page->page_image }}">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-row col-sm-12 padding_fix">
                    <div class="col-xs-12 col-sm-6">
                        <div class="col-xs-12 col-sm-12" style="border: 1px solid rgb(34,34,34); padding: 5px; background: #464646; z-index: 501;">
                            <span class="page1">Edit main description</span>
                        </div>
                        <textarea class="col-xs-12 col-sm-12 text-center page_desc1" name="page_desc1" required>{{ $page->description_1 }}</textarea>
                    </div>
                    <div class="col-xs-12 col-sm-6">
                        <div class="col-xs-12 col-sm-12 page_desc2_open" style="border: 1px solid rgb(34,34,34); padding: 5px; background: #464646; z-index: 501;">
                            <span class="page2">Edit additional description</span>
                        </div>
                        <textarea class="col-xs-12 col-sm-12 text-center page_desc2" name="page_desc2">{{ $page->description_2 }}</textarea>
                    </div>
                </div>
                <div class="form-row col-sm-12">
                    <div class="form-group col-xs-12 text-center">
                        <button class="btn btn-new" type="submit" value="Update page">Update</button>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@stop
@section('admin-scripts')
    <script type="text/javascript">

        $(document).ready( function() {
            $('.page_desc1').summernote({
                disableResizeEditor: false,
                placeholder: 'Main page description...'
            });
            $('.page_desc2').summernote({
                disableResizeEditor: false,
                placeholder: 'Additional page description...'
            });

        })

    </script>
@stop

resources/views/admin/cms_my_account.blade.php
@extends('admin.admin')
@section('admin-content')
    @include('admin.cms_admin_content_top')
    <div class="col-xs-12 users-content">
        <div class="row">
            <div class="col-xs-12" style="padding: 20px 15px;">
                <span style="font-size: 30px; font-weight: 600;">My account</span>
            </div>
            <div class="col-xs-12 padding_fix" style="padding-top: 20px;">
                {!! Form::open(array('route' => [ 'users.update', $user ], 'files' => 'true', 'method' => 'PUT' )) !!}
                {!! Form::token() !!}
                <div class="form-row col-xs-12 col-sm-3 col-md-3 padding_fix">
                    <div class="form-group col-xs-12 col-sm-12 padding_fix" style="padding-top: 10px;">
                        <div class="col-xs-12 col-sm-12 padding_fix" style="margin-bottom: 20px;">
                            @if ($errors->has('title'))
                                <div class="error" style="color: red; font-size: 12px;">
                                    {{ $errors->first('title') }}
                                </div>
                            @endif
                            <div class="col-xs-5 col-sm-4 text-right border-right-1">
                                <label class="new_user_label" for="inputTitle4">Username</label>
                            </div>
                            <div class="col-xs-7 col-sm-8 text-left">
                                <div>{{ $user->username }}</div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 padding_fix" style="margin-bottom: 20px;">
                            <div class="col-xs-5 col-sm-4 text-right border-right-1">
                                <label class="new_user_label" for="inputSeo4">Email</label>
                            </div>
                            <div class="col-xs-7 col-sm-8 text-left">
                                <div>{{ $user->email }}</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-row col-xs-12 col-sm-8 col-md-8 padding_fix">
                    <div class="form-group col-xs-12 col-sm-12" style="padding-top: 10px;">
                        <div class="col-xs-12 col-sm-12 flex_display padding_fix" style="margin-bottom: 10px;">

                        </div>
                    </div>
                </div>
                @if($user->super_admin == '1')
                <div class="form-row col-xs-12 col-sm-8 col-md-8 padding_fix">
                    <div class="form-group col-xs-12 col-sm-12" style="padding-top: 10px;">
                        <div class="col-xs-12 col-sm-12 flex_display padding_fix" style="margin-bottom: 10px;">
                            @if ($errors->has('new_email'))
                                <div class="error" style="color: red; font-size: 12px;">
                                    {{ $errors->first('new_email') }}
                                </div>
                            @endif
                            <div class="col-xs-2 padding_fix text-center">
                                <label class="new_user_label" for="inputEmail4">New email</label>
                            </div>
                            <div class="col-xs-10">
                                <input type="text" class="form-control" id="inputTitle4" name="new_email" placeholder="{{ $user->email }}" style="max-width: 200px;">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-row col-xs-12 col-sm-12 col-md-5">
                    <div class="form-group col-xs-12 text-center">
                        <button class="btn btn-new" type="submit" value="Update page">Update</button>
                    </div>
                </div>
                @endif
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@stop

resources/views/admin/sidebar.blade.php
<?php //SIDEBAR TOGGLE BUTTON ?>
<nav class="navbar navbar-expand-lg sidebar-toggler visible-xs visible-sm">
    <div class="container-fluid padding_fix">

        <button type="button" id="sidebarCollapse" class="btn btn-info" style="border-bottom-left-radius: 0px; border-top-left-radius: 0px;">
            <i class="fa fa-align-left"></i>
        </button>
    </div>
</nav>
<?php //TOGGLE BUTTON END ?>

<div class="sidebar-header text-center">
    <h3>almono's CMS application</h3>
</div>
<ul class="list-unstyled components admin-sidebar data-simplebar">
    @if(Auth::check())
        <li class="text-center" style="height: 150px; padding: 10px;">
            Logged as: <br>
            {{ Auth::user()->username }}
        </li>
        <li class="active">
            <a href="{{ route('admin') }}">Home</a>
        </li>
        <li>
            <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Models management<span class="caret"></span></a>
            <ul class="collapse list-unstyled" id="pageSubmenu2">
                <li>
                    <a href="{{ route('users.index') }}">Users</a>
                </li>
                <li>
                    <a href="{{ route('roles.index') }}">Roles</a>
                </li>
                <li>
                    <a href="{{ route('abilities.index') }}">Abilities</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Content management<span class="caret"></span></a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
                <li>
                    <a href="{{ route('menu.index') }}">Menu</a>
                </li>
                <li>
                    <a href="{{ route('pages.index') }}">Pages</a>
                </li>
                <li>
                    <a href="#">Website Footer</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="{{ route('admin_my_account') }}">My account</a>
        </li>
        <li>
            <a href="{{ route('admin_logout') }}">Log out</a>
        </li>
        <li class="text-center" style="position: absolute; bottom: 0; left: 0; right: 0;">
            <span style="font-size: 10px;">Made by Paweł Walczykiewicz</span>
        </li>
    @endif
</ul>