routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/admin/logout', ['uses' => 'Panel\UserController@admin_logout', 'as' => 'admin_logout']);

Route::get('/', 'Front\HomeController@index')->name('home');
Route::get('/admin', 'Panel\HomeController@panel')->name('admin');

//Panel routes
Route::group(['prefix' => 'admin'], function() {
    Route::resource('users','Panel\UserController');
    Route::resource('abilities','Panel\AbilityController');
    Route::resource('roles','Panel\RoleController');
    Route::resource('menu','Panel\MenuController');
    Route::resource('pages','Panel\PageController');
});

/* PANE ROUTES */

Route::post('/admin/change_active_user', 'Panel\UserController@changeActive');
Route::post('/admin/change_admin_user', 'Panel\UserController@changeAdmin');
Route::post('/admin/assign_new_role', ['uses' => 'Panel\UserController@assignrole','as' => 'assign_new_role']);
Route::post('/admin/remove_role/{user}/{role_name}', ['uses' => 'Panel\UserController@removeRole','as' => 'remove_role']);

Route::post('/admin/change_active_role', 'Panel\RoleController@changeActive');
Route::post('/admin/assign_new_ability', ['uses' => 'Panel\RoleController@assignAbility','as' => 'assign_new_ability']);
Route::post('/admin/remove_ability/{role_name}/{ability_id}', ['uses' => 'Panel\RoleController@removeAbility','as' => 'remove_ability']);

Route::post('/admin/change_active_ability', 'Panel\AbilityController@changeActive');

Route::post('/admin/change_active_menu', 'Panel\MenuController@changeActive');

Route::post('/admin/change_active_page', 'Panel\PageController@changeActive');

Route::get('/admin/new_page', ['uses' => 'Panel\PageController@newPage', 'as' => 'new_page_form']);
Route::get('/admin/my_account', ['uses' => 'Panel\UserController@getMyAccount', 'as' => 'admin_my_account']);

/* FRONT ROUTES */

Route::get('/about-me', ['uses' => 'Front\HomeController@aboutMe', 'as' => 'about-me']);
Route::get('/page/download/{filename}', ['uses' => 'Front\HomeController@downloadFile', 'as' => 'download_file']);
Route::get('/page/{page_slug}', ['uses' => 'Front\PageController@showPage', 'as' => 'show_page']);

Route::get('/generate-sitemap', ['uses' => 'Front\HomeController@generateSitemap', 'as' => 'generate_sitemap']);

resources/views/admin/partials/cms_ability_listing.blade.php
@foreach($abilities as $a)
    <div class="col-xs-12 padding_fix text-center" style="color: white; padding-top: 10px; padding-bottom: 10px; @if(!$loop->last) border-bottom: 1px solid #222; @endif">
        <div class="col-xs-12 col-sm-12 col-md-2 padding_fix">
            {{ $a->title }}
        </div>
        <div class="col-xs-6 col-sm-6 col-md-1 padding_fix">
            <div class="pretty p-default p-thick p-pulse" style="margin-right: -5px;">
                <input type="checkbox" class="admin-checkbox is-active" name="is_active" id="{{$a->id}}" @if($a->active == '1') checked="checked"  @endif >
                <div class="state p-success-o">
                    <label></label>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-2 padding_fix hidden-xs hidden-sm">
            {{ $a->created_at }}
        </div>
        <div class="col-xs-6 col-sm-6 col-md-1 padding_fix">
            {!! Form::open(['route' => ['abilities.destroy', $a->id], 'method' => 'delete', 'onsubmit' => 'return ConfirmDelete()']) !!}
            <button type="submit" style="background: transparent; border: none;">
                <i class="fa fa-times" style="font-size: 16px; color: red;"></i>
            </button>
            {!! Form::close() !!}
        </div>
    </div>
@endforeach
<div class="col-xs-12 text-right">
    @if($abilities->render() != "")
        {!! $abilities->render() !!}
    @endif
</div>

resources/views/admin/partials/cms_menu_item_listing.blade.php
@foreach($menu as $m)
    <div class="col-xs-12 padding_fix text-center" style="color: white; padding-top: 10px; padding-bottom: 10px; @if(!$loop->last) border-bottom: 1px solid #222; @endif">
        <div class="col-xs-12 col-md-1 padding_fix hidden-xs hidden-sm">
            {{ $m->id }}
        </div>
        <div class="col-xs-6 col-md-2 padding_fix m-5-bottom">
            {{ $m->menu_name }}
        </div>
        <div class="col-xs-6 col-md-2 padding_fix m-5-bottom">
            @if($m->parent_id == 0 || !isset($m->parent))
                -
            @else
                {{ $m->parent->menu_name }}
            @endif
        </div>
        <div class="col-xs-6 col-md-1 padding_fix m-5-bottom">
            <div class="pretty p-default p-thick p-pulse" style="margin-right: -5px;">
                <input type="checkbox" class="admin-checkbox is-active" name="is_active" id="{{$m->id}}" @if($m->active == '1') checked="checked"  @endif >
                <div class="state p-success-o">
                    <label></label>
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-md-2 padding_fix m-5-bottom">
            @if($m->menu_url == "" || !isset($m->menu_url))
                -
            @else
                {{ $m->menu_url }}
            @endif
        </div>
        <div class="col-xs-12 col-md-1 text-center hidden-xs hidden-sm">
            {{ $m->order }}
        </div>
        <div class="col-xs-6 col-md-1 text-center m-5-bottom">
            <a href="{{ route('menu.show', $m->id) }}">
                <i class="fa fa-edit" style="font-size: 18px; color: lightgreen;"></i>
            </a>
        </div>
        <div class="col-xs-6 col-md-1 text-center m-5-bottom">
            {!! Form::open(['route' => ['menu.destroy', $m->id], 'method' => 'delete', 'onsubmit' => 'return ConfirmDelete()']) !!}
            <button type="submit" style="background: transparent; border: none;">
                <i class="fa fa-times" style="font-size: 16px; color: red;"></i>
            </button>
            {!! Form::close() !!}
        </div>
    </div>
@endforeach
<div class="col-xs-12 text-right">
    @if($menu->render() != "")
        {!! $menu->render() !!}
    @endif
</div>

resources/views/admin/partials/cms_page_listing.blade.php
@foreach($pages as $p)
    <div class="col-xs-12 padding_fix text-center" style="color: white; padding-top: 10px; padding-bottom: 10px;">
        <div class="col-xs-12 col-md-1 padding_fix hidden-xs hidden-sm">
            {{ $p->id }}
        </div>
        <div class="col-xs-12 col-md-2 padding_fix">
            {{ $p->page_title }}
        </div>
        <div class="col-xs-4 col-md-1 padding_fix">
            <div class="pretty p-default p-thick p-pulse" style="margin-right: -5px;">
                <input type="checkbox" class="admin-checkbox is-active" name="is_active" id="{{$p->id}}" @if($p->active == '1') checked="checked" @endif >
                <div class="state p-success-o">
                    <label></label>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-2 padding_fix hidden-xs hidden-sm">
            {{ $p->created_at }}
        </div>
        <div class="col-xs-4 col-md-1 padding_fix">
            <a href="{{ route('pages.show', $p->id) }}">
                <i class="fa fa-edit" style="font-size: 18px; color: lightgreen;"></i>
            </a>
        </div>
        <div class="col-xs-4 col-md-1 text-center">
            {!! Form::open(['route' => ['pages.destroy', $p->id], 'method' => 'delete', 'onsubmit' => 'return ConfirmDelete()']) !!}
            <button type="submit" style="background: transparent; border: none;">
                <i class="fa fa-times" style="font-size: 16px; color: red;"></i>
            </button>
            {!! Form::close() !!}
        </div>
    </div>
@endforeach
<div class="col-xs-12 text-right">
    @if($pages->render() != "")
        {!! $pages->render() !!}
    @endif
</div>

resources/views/admin/partials/cms_role_listing.blade.php
@foreach($roles as $r)
    <div class="col-xs-12 padding_fix text-center listing_div" style="color: white; padding-top: 10px; padding-bottom: 10px; @if(!$loop->last) border-bottom: 1px solid #222; @endif">
        <div class="col-xs-12 col-sm-12 col-md-2 padding_fix">
            {{ $r->title }}
        </div>
        <div class="col-xs-4 col-sm-4 col-md-1 padding_fix">
            <div class="pretty p-default p-thick p-pulse" style="margin-right: -5px;">
                <input type="checkbox" class="admin-checkbox is-active" name="is_active" id="{{$r->id}}" @if($r->active == '1') checked="checked"  @endif >
                <div class="state p-success-o">
                    <label></label>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-2 padding_fix hidden-xs hidden-sm">
            {{ $r->created_at }}
        </div>
        <div class="col-xs-4 col-sm-4 col-md-1 padding_fix listing_edit">
            <a href="{{ route('roles.show', $r->id) }}">
                <i class="fa fa-edit" style="font-size: 18px; color: lightgreen;"></i>
            </a>
        </div>
        <div class="col-xs-4 col-sm-4 col-md-1 padding_fix">
            {!! Form::open(['route' => ['roles.destroy', $r->id], 'method' => 'delete', 'onsubmit' => 'return ConfirmDelete()']) !!}
            <button type="submit" style="background: transparent; border: none;">
                <i class="fa fa-times" style="font-size: 16px; color: red;"></i>
            </button>
            {!! Form::close() !!}
        </div>
    </div>
@endforeach
<div class="col-xs-12 text-right">
    @if($roles->render() != "")
        {!! $roles->render() !!}
    @endif
</div>

resources/views/admin/partials/cms_user_listing.blade.php
@foreach($users as $u)
    <div class="col-xs-12 padding_fix text-center" style="color: white; padding-top: 10px; padding-bottom: 10px; @if(!$loop->last) border-bottom: 1px solid #222; @endif">
        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-2 padding_fix">
            {{ $u->username }}
        </div>
        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-2 padding_fix">
            {{ $u->email }}
        </div>
        <div class="col-xs-6 col-sm-6 col-md-1 col-lg-1 padding_fix">
            <div class="pretty p-default p-thick p-pulse" style="margin-right: -5px;">
                <input type="checkbox" class="admin-checkbox is-active" name="is_active" id="{{$u->id}}" @if($u->active == '1') checked="checked"  @endif >
                <div class="state p-success-o">
                    <label></label>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-2 col-lg-1 padding_fix hidden-xs hidden-sm">
            <div class="pretty p-default p-thick p-pulse" style="margin-right: -5px;">
                <input type="checkbox" class="admin-checkbox is-admin" name="is_admin" id="{{$u->id}}" @if($u->super_admin == '1') checked="checked" @endif >
                <div class="state p-success-o">
                    <label></label>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-2 col-lg-1 padding_fix hidden-xs hidden-sm">
            {{ $u->created_at }}
        </div>
        <div class="col-xs-6 col-sm-6 col-md-1 col-lg-1 padding_fix">
            <a href="{{ route('users.show', $u->id) }}">
                <i class="fa fa-edit" style="font-size: 18px; color: lightgreen;"></i>
            </a>
        </div>
    </div>
@endforeach
<div class="col-xs-12 text-right">
    @if($users->render() != "")
        {!! $users->render() !!}
    @endif
</div>